
```{r setup, include=FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

# Missing values

"Describe any patterns you discover in missing values.

(suggested: 2 graphs plus commentary)“




```{r}
# from chapter 2&3
data1.0 <- read.csv("1 visitor trend-不分state.csv")[-c(7:11),]
data2.0 <- read.csv("2 visitor trend-分state.csv")[-c(301:305),]
data2.10<- read.csv("2.1 visitor trend- state plus dest.csv")[-c(1051:1054),]
data3.0 <- read.csv("3 destination.csv")[-c(29:32),]
data4.0 <- read.csv("4 Q2主要数据.csv")[-c(217:221),]

library(tidyverse)
library(dplyr)

empty_as_na <- function(x){
    if("factor" %in% class(x)) x <- as.character(x) ## since ifelse wont work with factors
    #ifelse(as.character(x)!="", x, NA)
    ifelse(x!="", x, NA)
}


data1<- data1.0 %>% 
  mutate_each(funs(empty_as_na)) %>%
  pivot_longer(cols = -c("Market", "Indicator", "Units", "Destination"),
               names_to = "Year",
               values_to = "number")  %>%
  mutate(Year = substr(Year, 2, 1000)) %>%
  pivot_wider(names_from = "Year",
              values_from = "number")

data2<- data2.0 %>% 
  mutate_each(funs(empty_as_na)) %>%
  pivot_longer(cols = -c("Market", "Indicator", "Units", "Destination"),
               names_to = "Year",
               values_to = "number")  %>%
  mutate(Year = substr(Year, 2, 1000)) %>%
  pivot_wider(names_from = "Year",
              values_from = "number")

data2.1<- data2.10 %>% 
  mutate_each(funs(empty_as_na)) %>%
  pivot_longer(cols = -c("Market", "Indicator", "Units", "Destination"),
               names_to = "Year",
               values_to = "number")  %>%
  mutate(Year = substr(Year, 2, 1000)) %>%
  pivot_wider(names_from = "Year",
              values_from = "number")


data3<- data3.0 %>% 
  mutate_each(funs(empty_as_na)) %>%
  pivot_longer(cols = -c("Market", "Indicator", "Units", "Destination"),
               names_to = "Year",
               values_to = "number")  %>%
  mutate(Year = substr(Year, 2, 1000)) %>%
  pivot_wider(names_from = "Year",
              values_from = "number")


data4<- data4.0 %>%
  pivot_longer(cols = -c("Group", "Indicator", "Units"),
               names_to = "Year",
               values_to = "number")  %>%
  mutate(Year = substr(Year, 2, 1000)) %>%
  pivot_wider(names_from = "Year",
              values_from = "number")

d1<- tibble(data1[,-c(5:21)][,-c(3)][,c(1,2,3,8)])
d2<- tibble(data2[,-c(5:21)]) 
d2.1<- tibble(data2.1)[,-c(5:21)][,c(1,2,3,4,8)]
d4<- tibble(data4.0[,-c(4:19)][,c(1, 2, 8)])
```

```{r}
empty_as_na <- function(x){
    if("factor" %in% class(x)) x <- as.character(x) ## since ifelse wont work with factors
    #ifelse(as.character(x)!="", x, NA)
    ifelse(x!="", x, NA)
}

missing1 <- data1 %>%
  rownames_to_column("id") %>%
  gather(key, value, -id) %>% 
  mutate(missing = ifelse(is.na(value), "yes", "no")) %>% 
  group_by(key) %>% 
  summarise(sum.na = sum(is.na(value)))

#ggplot(missing1, aes(x = key, y = sum.na)) +
#  geom_col(color = "blue", fill = "lightblue") +
#  #scale_x_continuous(breaks = 1:28, labels = missing$key) +
#  ggtitle("Number of missing values by day") +
#  xlab("") +
#  ylab("") +
#  theme(axis.text.x = element_text(angle = 90))

data1 %>%
  pivot_longer(cols = -c("Market", "Indicator", "Units", "Destination"),
               names_to = "Year",
               values_to = "number") %>%
  mutate(missing = ifelse(is.na(number), "yes", "no")) %>%
  ggplot(aes(x = Indicator, y = Year, fill = missing)) +
  geom_tile(color = "white") 
```


```{r}
missing2 <- data2 %>%
  rownames_to_column("id") %>%
  gather(key, value, -id) %>% 
  mutate(missing = ifelse(is.na(value), "yes", "no")) %>% 
  group_by(key) %>% 
  summarise(sum.na = sum(is.na(value)))

#ggplot(missing2, aes(x = key, y = sum.na)) +
#  geom_col(color = "blue", fill = "lightblue") +
#  #scale_x_continuous(breaks = 1:28, labels = missing$key) +
#  ggtitle("Number of missing values by day") +
#  xlab("") +
#  ylab("") +
#  theme(axis.text.x = element_text(angle = 90))

data2 %>%
  pivot_longer(cols = -c("Market", "Indicator", "Units", "Destination"),
               names_to = "Year",
               values_to = "number") %>%
  mutate(missing = ifelse(is.na(number), "yes", "no")) %>%
  ggplot(aes(x = Indicator, y = Year, fill = missing)) +
  geom_tile(color = "white") 
```


```{r}
missing2.1 <- data2.1 %>%
  rownames_to_column("id") %>%
  gather(key, value, -id) %>% 
  mutate(missing = ifelse(is.na(value), "yes", "no")) %>% 
  group_by(key) %>% 
  summarise(sum.na = sum(is.na(value)))

#ggplot(missing2.1, aes(x = key, y = sum.na)) +
#  geom_col(color = "blue", fill = "lightblue") +
#  #scale_x_continuous(breaks = 1:28, labels = missing$key) +
#  ggtitle("Number of missing values by day") +
#  xlab("") +
#  ylab("") +
#  theme(axis.text.x = element_text(angle = 90))

data2.1 %>%
  pivot_longer(cols = -c("Market", "Indicator", "Units", "Destination"),
               names_to = "Year",
               values_to = "number") %>%
  mutate(missing = ifelse(is.na(number), "yes", "no")) %>%
  ggplot(aes(x = Indicator, y = Year, fill = missing)) +
  geom_tile(color = "white") 
```


```{r}
missing3 <- data3 %>%
  rownames_to_column("id") %>%
  gather(key, value, -id) %>% 
  mutate(missing = ifelse(is.na(value), "yes", "no")) %>% 
  group_by(key) %>% 
  summarise(sum.na = sum(is.na(value)))

#ggplot(missing3, aes(x = key, y = sum.na)) +
#  geom_col(color = "blue", fill = "lightblue") +
#  #scale_x_continuous(breaks = 1:28, labels = missing$key) +
#  ggtitle("Number of missing values by day") +
#  xlab("") +
#  ylab("") +
#  theme(axis.text.x = element_text(angle = 90))

data3 %>%
  pivot_longer(cols = -c("Market", "Indicator", "Units", "Destination"),
               names_to = "Year",
               values_to = "number") %>%
  mutate(missing = ifelse(is.na(number), "yes", "no")) %>%
  ggplot(aes(x = Indicator, y = Year, fill = missing)) +
  geom_tile(color = "white") 
```


```{r fig.width = 7, fig.height = 7}
tidy4<- data4 %>%
  rownames_to_column("id") %>%
  gather(key, value, -id) %>% 
  mutate(missing = ifelse(is.na(value), "yes", "no"))

missing4 <- tidy4 %>% 
    group_by(key) %>% 
    summarise(sum.na = sum(is.na(value)))

ggplot(missing4, aes(x = key, y = sum.na)) +
  geom_col(color = "blue", fill = "lightblue") +
  #scale_x_continuous(breaks = 1:28, labels = missing$key) +
  ggtitle("Number of missing values by day") +
  xlab("") +
  ylab("") +
  theme(axis.text.x = element_text(angle = 90))

#indicator missing
data4 %>%
  pivot_longer(cols = -c("Group", "Indicator", "Units"),
               names_to = "Year",
               values_to = "number") %>%
  mutate(missing = ifelse(is.na(number), "yes", "no")) %>%
  ggplot(aes(x = Indicator, y = Year, fill = missing)) +
  geom_tile(color = "white") +
  theme(axis.text.x = element_text(angle = 90))
```
```{r}
#group missing
data4 %>%
  pivot_longer(cols = -c("Group", "Indicator", "Units"),
               names_to = "Year",
               values_to = "number") %>%
  mutate(missing = ifelse(is.na(number), "yes", "no")) %>%
  ggplot(aes(x = Group, y = Year, fill = missing)) +
  geom_tile(color = "white") +
  theme(axis.text.x = element_text(angle = 10))
```
