# Conclusion

From the our analysis, we have got several useful conclusions about our trip planning to Hawaii and could answer the three questions directly.

Firstly, our age compared to the visitors' average age of Hawaii is too young. As we can see, most people who travel to Hawaii are 40-50 years old, which means either Hawaii is more suitable for middle aged people, or the cost of the travel is too high for young people to afford. If we really want to go to Hawaii for fun, we may choose Maui and Oahu island as our target destination because visitors in those two islands tend to be younger. Considering the time of our trip, we may probably choose some time from May to September because the scenery may be the best during the high season. Oppositely, if someone wants to avoid the crowd, September or January can be a good traveling time. 

Secondly, for our travel plan, since we are for a vacation, Maui and Oahu island can be our ideal destination, especially for Maui as more people choose to spend more time there. If someone wants to get married or spend a honeymoon, Oahu island could be a perfect choice. Molokai island is not a very good choice for traveling as most people go there for visiting friends or relatives, so as Lanai island because not a lot of people would go there. These two places may be deleted from our destination list. For accommodation, we should choose to live in hotels in Oahu island and consider condos in Maui island if we follow the general trend. 

Thirdly, the number of people traveling to Hawaii is greatly impacted by the environment and economy. We see that much less people come for vacation during the economic crisis in 2008, and the pandemic in 2020. In 2020, there was nearly no tourist in Hawaii even during the most popular tourist season: May to September. We can say the pandemic did destroy the tourism of Hawaii at that time.

Except from these findings, there are many other findings we discussed in the results section that are not direct used for answering our three questinos. And also there are some flaws in our report indeed. For example, we mainly used data in 2019 for analysis in question 1 and 2 due to the missing data in our dataset. This is not accurate enough as the tourist pattern could differ from year to year. If given more time and resource, we could make a report for each year and develop more precise conclusions or make it interactively with the button choosing the year. 

In this report, we got a better understanding of how graphs could provide us with a more intuitive understanding of the data we have. From the process of making interactive plot, we prefect our debugging skills and became better at making html interactive graphics, which is a good practice for future preparation. 