--- 
title: "Hawaii Travel Data Visualization"
author: "Yige Chen, WeiJia Wang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

For this report, We are interested in taking Hawaii as our travel destination for summer or spring break. As the tourism of Hawaii is well developed, we believe there should be enough data collected that can help us to explore the development of the tourism of Hawaii.

Here we come up with three questions:

1. What kind of people like going to Hawaii for vacation, is Hawaii a good travel destination for students like us?

2. Can we make a perfect travel plan based on the activities of other tourists?

3. Is the tourism of Hawaii influenced by the pandemic? If it is, how bad?

To help solve the problems, we searched Hawaii Tourism public data on Google and found a tourism data warehouse that enables us to customize and download data sets about Hawaii’s tourism industry in difference perspectives. We believe the open data website contains enough information for us to answer our questions, for example:

For question 1, we can explore the features of tourists by downloading data sets containing their basic information like age, gender, departure place, travel purposes, their daily expenditure in Hawaii, etc.. If it is the majority of visitors are younger people who come from all over the world (meaning a safe place), the money their average expenditure is not high for us, then maybe we could consider Hawaii as a affordable destination.

For question 2, we can make the travel plan based on what islands do most people go, what activities do they do on each island and the average time they spend there. All these data could be found on the official data website.

For question 3, we may explore this question by studying if the answers of the two previous questions (or the pattern of the two data sets) have changed in the past two years. Since we have all the data from 1990 to 2021, we may not be limited to the pandemic period, but to do the data analyse for the whole time period.
