---
title: "FinalProject"
author: "Yige Chen, Weijia WangS"
date: "2022/4/25"
output: html_document
---

笔记：
Q3 细分，哪些州收到covid影响较小

Q3 Pset4 facet grid年份-季节趋势图

Q1可以用表4中的first time visitor与否、age

length of stay在表3

```{r setup, include=FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
data1.0 <- read.csv("1 visitor trend-不分state.csv")[-c(7:11),]
data2.0 <- read.csv("2 visitor trend-分state.csv")[-c(301:305),]
data2.10<- read.csv("2.1 visitor trend- state plus dest.csv")[-c(1051:1054),]
data3.0 <- read.csv("3 destination.csv")[-c(29:32),]
data4.0 <- read.csv("4 Q2主要数据.csv")[-c(217:221),]

library(tidyverse)
library(dplyr)
```




**Missing Data**
```{r} 
## define a helper function
empty_as_na <- function(x){
    if("factor" %in% class(x)) x <- as.character(x) ## since ifelse wont work with factors
    #ifelse(as.character(x)!="", x, NA)
    ifelse(x!="", x, NA)
}
```


```{r}
data1<- data1.0 %>% 
  mutate_each(funs(empty_as_na)) %>%
  pivot_longer(cols = -c("Market", "Indicator", "Units", "Destination"),
               names_to = "Year",
               values_to = "number")  %>%
  mutate(Year = substr(Year, 2, 1000)) %>%
  pivot_wider(names_from = "Year",
              values_from = "number")

missing1 <- data1 %>%
  rownames_to_column("id") %>%
  gather(key, value, -id) %>% 
  mutate(missing = ifelse(is.na(value), "yes", "no")) %>% 
  group_by(key) %>% 
  summarise(sum.na = sum(is.na(value)))

#ggplot(missing1, aes(x = key, y = sum.na)) +
#  geom_col(color = "blue", fill = "lightblue") +
#  #scale_x_continuous(breaks = 1:28, labels = missing$key) +
#  ggtitle("Number of missing values by day") +
#  xlab("") +
#  ylab("") +
#  theme(axis.text.x = element_text(angle = 90))

data1 %>%
  pivot_longer(cols = -c("Market", "Indicator", "Units", "Destination"),
               names_to = "Year",
               values_to = "number") %>%
  mutate(missing = ifelse(is.na(number), "yes", "no")) %>%
  ggplot(aes(x = Indicator, y = Year, fill = missing)) +
  geom_tile(color = "white") 

```

```{r}
data2<- data2.0 %>% 
  mutate_each(funs(empty_as_na)) %>%
  pivot_longer(cols = -c("Market", "Indicator", "Units", "Destination"),
               names_to = "Year",
               values_to = "number")  %>%
  mutate(Year = substr(Year, 2, 1000)) %>%
  pivot_wider(names_from = "Year",
              values_from = "number")

missing2 <- data2 %>%
  rownames_to_column("id") %>%
  gather(key, value, -id) %>% 
  mutate(missing = ifelse(is.na(value), "yes", "no")) %>% 
  group_by(key) %>% 
  summarise(sum.na = sum(is.na(value)))

#ggplot(missing2, aes(x = key, y = sum.na)) +
#  geom_col(color = "blue", fill = "lightblue") +
#  #scale_x_continuous(breaks = 1:28, labels = missing$key) +
#  ggtitle("Number of missing values by day") +
#  xlab("") +
#  ylab("") +
#  theme(axis.text.x = element_text(angle = 90))

data2 %>%
  pivot_longer(cols = -c("Market", "Indicator", "Units", "Destination"),
               names_to = "Year",
               values_to = "number") %>%
  mutate(missing = ifelse(is.na(number), "yes", "no")) %>%
  ggplot(aes(x = Indicator, y = Year, fill = missing)) +
  geom_tile(color = "white") 
```

```{r}
data2.1<- data2.10 %>% 
  mutate_each(funs(empty_as_na)) %>%
  pivot_longer(cols = -c("Market", "Indicator", "Units", "Destination"),
               names_to = "Year",
               values_to = "number")  %>%
  mutate(Year = substr(Year, 2, 1000)) %>%
  pivot_wider(names_from = "Year",
              values_from = "number")

missing2.1 <- data2.1 %>%
  rownames_to_column("id") %>%
  gather(key, value, -id) %>% 
  mutate(missing = ifelse(is.na(value), "yes", "no")) %>% 
  group_by(key) %>% 
  summarise(sum.na = sum(is.na(value)))

#ggplot(missing2.1, aes(x = key, y = sum.na)) +
#  geom_col(color = "blue", fill = "lightblue") +
#  #scale_x_continuous(breaks = 1:28, labels = missing$key) +
#  ggtitle("Number of missing values by day") +
#  xlab("") +
#  ylab("") +
#  theme(axis.text.x = element_text(angle = 90))

data2.1 %>%
  pivot_longer(cols = -c("Market", "Indicator", "Units", "Destination"),
               names_to = "Year",
               values_to = "number") %>%
  mutate(missing = ifelse(is.na(number), "yes", "no")) %>%
  ggplot(aes(x = Indicator, y = Year, fill = missing)) +
  geom_tile(color = "white") 

```

```{r}
data3<- data3.0 %>% 
  mutate_each(funs(empty_as_na)) %>%
  pivot_longer(cols = -c("Market", "Indicator", "Units", "Destination"),
               names_to = "Year",
               values_to = "number")  %>%
  mutate(Year = substr(Year, 2, 1000)) %>%
  pivot_wider(names_from = "Year",
              values_from = "number")

missing3 <- data3 %>%
  rownames_to_column("id") %>%
  gather(key, value, -id) %>% 
  mutate(missing = ifelse(is.na(value), "yes", "no")) %>% 
  group_by(key) %>% 
  summarise(sum.na = sum(is.na(value)))

#ggplot(missing3, aes(x = key, y = sum.na)) +
#  geom_col(color = "blue", fill = "lightblue") +
#  #scale_x_continuous(breaks = 1:28, labels = missing$key) +
#  ggtitle("Number of missing values by day") +
#  xlab("") +
#  ylab("") +
#  theme(axis.text.x = element_text(angle = 90))

data3 %>%
  pivot_longer(cols = -c("Market", "Indicator", "Units", "Destination"),
               names_to = "Year",
               values_to = "number") %>%
  mutate(missing = ifelse(is.na(number), "yes", "no")) %>%
  ggplot(aes(x = Indicator, y = Year, fill = missing)) +
  geom_tile(color = "white") 
```


```{r fig.width = 7, fig.height = 7}
data4<- data4.0 %>%
  pivot_longer(cols = -c("Group", "Indicator", "Units"),
               names_to = "Year",
               values_to = "number")  %>%
  mutate(Year = substr(Year, 2, 1000)) %>%
  pivot_wider(names_from = "Year",
              values_from = "number")

tidy4<- data4 %>%
  rownames_to_column("id") %>%
  gather(key, value, -id) %>% 
  mutate(missing = ifelse(is.na(value), "yes", "no"))

missing4 <- tidy4 %>% 
    group_by(key) %>% 
    summarise(sum.na = sum(is.na(value)))

ggplot(missing4, aes(x = key, y = sum.na)) +
  geom_col(color = "blue", fill = "lightblue") +
  #scale_x_continuous(breaks = 1:28, labels = missing$key) +
  ggtitle("Number of missing values by day") +
  xlab("") +
  ylab("") +
  theme(axis.text.x = element_text(angle = 90))

#indicator missing
data4 %>%
  pivot_longer(cols = -c("Group", "Indicator", "Units"),
               names_to = "Year",
               values_to = "number") %>%
  mutate(missing = ifelse(is.na(number), "yes", "no")) %>%
  ggplot(aes(x = Indicator, y = Year, fill = missing)) +
  geom_tile(color = "white") +
  theme(axis.text.x = element_text(angle = 90))

#group missing
data4 %>%
  pivot_longer(cols = -c("Group", "Indicator", "Units"),
               names_to = "Year",
               values_to = "number") %>%
  mutate(missing = ifelse(is.na(number), "yes", "no")) %>%
  ggplot(aes(x = Group, y = Year, fill = missing)) +
  geom_tile(color = "white") +
  theme(axis.text.x = element_text(angle = 10))

```






```{r}
d1<- tibble(data1[,-c(5:21)][,-c(3)][,c(1,2,3,8)])
d2<- tibble(data2[,-c(5:21)]) 
d2.1<- tibble(data2.1)[,-c(5:21)][,c(1,2,3,4,8)]
d4<- tibble(data4.0[,-c(4:19)][,c(1, 2, 8)])
```

```{r}
d4.1<- d4 %>%
  filter(Group != "Visitor from US") %>%
  na.omit() %>%
  pivot_wider(names_from = Indicator, values_from = X2019) 
  
d4.1 %>%
  mutate(Group = factor(Group, levels = c("Oahu visitors", 
                                          "Maui visitors",
                                          "Hawaii ISL visitors",
                                          "Kauai visitors",
                                          "Lanai visitors",
                                          "Molokai visitors"))) %>%
  ggplot(aes(x = Group, y = `Avg. age of party head`)) +
  geom_col(fill = "cornflowerblue") +
  coord_flip() 


d4.1[,c(1,3,4)] %>%
  pivot_longer(c(`First timer (%)`, `Repeaters (%)`), 
               names_to ="Times of come", 
               values_to = "percentage") %>%
  ggplot(aes(x = Group, y = percentage, fill = `Times of come`)) +
  geom_col() 
```



```{r}

purpose<- cbind(d4.1[,c(1)], d4.1[c(grep("Purpose",colnames(d4.1)))])%>%
  pivot_longer(c(2:16), 
               names_to ="Purpose", 
               values_to = "percentage") %>%
  mutate(Purpose = substr(Purpose, 10, 1000)) %>%
  mutate(Purpose = gsub('.{4}$', '', Purpose)) %>%
  filter(Purpose %in% c("Vacation", "Honeymoon/Get married", "Visit Friends/Relative")) %>%
  pivot_wider(names_from = Purpose, 
              values_from = percentage) %>%
  mutate(OtherPurpose = 100 - Vacation - `Honeymoon/Get married` - `Visit Friends/Relative`) %>%
  pivot_longer(c(2:5),
               names_to = "Purpose",
               values_to = "percentage")

purpose %>%
  ggplot(aes(x = Group, y = percentage, fill = Purpose)) +
  geom_col()  +
  theme(axis.text.x = element_text(angle = 10, vjust = 0.5, hjust=1))



Accom<- cbind(d4.1[,c(1)], d4.1[c(grep("Accom",colnames(d4.1)))]) %>%
  pivot_longer(c(2:14), 
               names_to ="Accomodation", 
               values_to = "percentage") %>%
  mutate(Accomodation = substr(Accomodation, 8, 1000)) %>%
  mutate(Accomodation = gsub('.{4}$', '', Accomodation)) %>%
  filter(Accomodation %in% c("Hotel only", "Condo", "Friends/Relatives", "Rental house")) %>%
  pivot_wider(names_from = Accomodation, 
              values_from = percentage) %>%
  mutate(OtherAccomodation = 100 - `Hotel only` - `Condo` - `Friends/Relatives` - `Rental house`) %>%
  pivot_longer(c(2:6),
               names_to = "Accomodation",
               values_to = "percentage")

Accom %>%
  ggplot(aes(x = Group, y = percentage, fill = Accomodation)) +
  geom_col() +
    theme(axis.text.x = element_text(angle = 10, vjust = 0.5, hjust=1))
```


```{r}  
library(treemap)

d3<- tibble(data3[,-c(5:29)][,c(1,2,3,4,9)])
colnames(d3)[5] <- 'Year_2019'
d3$Year_2019<- as.numeric(gsub(",","", d3$Year_2019))

d3 %>%
  filter(Indicator == "Visitor arrivals") %>%
  select( -c(Market, Units)) %>%
  treemap::treemap(index=c("Destination"),
                   vSize="Year_2019",
                   vColor="Year_2019",
                   type="value",
                   title="Number of visitors to different islands",  
                   format.legend = list(scientific = FALSE, big.mark = " ")) 
  
d3 %>%
  filter(Indicator == "Length of stay") %>%
  select( -c(Market, Units)) %>%
  treemap::treemap(index=c("Destination"),
                   vSize="Year_2019",
                   vColor="Year_2019",
                   type="value",
                   title="Length of stay for visitors to different islands",  
                   format.legend = list(scientific = FALSE, big.mark = " ")) 
```


```{r}
#devtools::install_github("timelyportfolio/parcoords")  
#install.packages("d3r")
library(parcoords)  
library(d3r)

colnames(d2.1)[5] <- 'Year_2019'

g<- d2.1 %>%
  filter(Indicator == "Visitor arrivals") %>%
  dplyr::select(Destination, Market, Year_2019) %>%
  pivot_wider(names_from = Destination,
              values_from = Year_2019) 
g1 <- data.frame(t(data.frame(matrix(unlist(g), nrow=length(g), byrow=TRUE))))
colnames(g1)<- names(g)

library(GGally)
ggparcoord(g1, columns = 2:8, scale = "center", alphaLines = .7, splineFactor = 10, groupColumn = 1) +
 # geom_vline(xintercept = 2:7, color = "lightblue") +
  theme(legend.title = element_text(size = 5), legend.text = element_text(size = 5))

interactive<- g1 %>%
  parcoords(  
    rownames = F     #   turn off rownames from the data.frame  
    , brushMode = "1D-axes"  
    , reorderable = T  
    , queue = T  
    , withD3 = TRUE     
  )
interactive
```















